plentymarkets/plentymarkets-shopware-connector

Components/Import/Entity/PlentymarketsImportEntityItem.php
If a "Merkmal" is from type "Auswahl" use the SelectionName as PropertyValue.
=> [FEATURE] Use SelectionName as PropertyValue

Components/Import/Entity/Order/PlentymarketsImportEntityItemBundle.php
https://www.plentymarkets.eu/forum/shopware/Fehler-beim-Datenaustausch-Artikelpakete/
=> fix bundle import

Components/Utils/PlentymarketsTranslation.php
@joconja 
Bug fixed: import translations
=> UPDATE PlentymarketsTranslation : getShopActiveLanguages()

Components/Import/Entity/PlentymarketsImportEntityItemImage.php
=> FIX: GetItemsImage Soap Call Response

Bootstrap.php, Components/Soap/Client/PlentymarketsSoapClient.php
=> UPDATE : PlentymarketsSoapClient : check soap calls limit per minute

Components/Soap/Client/PlentymarketsSoapClient.php
=> UPDATE PlentymarketsSoapClient: update sopa calls counter

Components/Export/Entity/PlentymarketsExportEntityCustomer.php, Controllers/Backend/Plentymarkets.php, Views/backend/plentymarkets/model/settings.js, Views/backend/plentymarkets/view/settings.js
=> UPDATE Export of customer

Components/Import/Entity/PlentymarketsImportEntityItem.php, Components/Import/Entity/PlentymarketsImportEntityItemPrice.php
I needed a way to customize some small portions of the connector used during the import and update of items. For that i introduced some small filter events to hook into.
=> Use Shopware's eventsystem during the import

Components/Utils/PlentymarketsUtils.php
Rua Oscar da Silva 1559 could not be exportet
=> support House number with 4 digits

Components/Import/Entity/PlentymarketsImportEntityItem.php
This add the plenty article main category of a plenty shop as shopware article seo category.
=> add article seo categories

Controller/Backend/PlentyConnector.php, Resources/Views/backend/plenty_connector/view/mapping/tab.js
- erlaubt das löschen von Mappings
- passt das Verhalten der Comboboxen an
=> Anpassung Mapping Tab

Controller/Backend/PlentyConnector.php, Resources/Views/backend/plenty_connector/controller/mapping.js, Resources/Views/backend/plenty_connector/model/mapping/information.js, Resources/Views/backend/plenty_connector/model/mapping/row.js, Resources/Views/backend/plenty_connector/view/mapping/tab.js
Fixes issues while deleting mappings or creating duplicate entries.
=> Backend mapping logic refactored

Components/Import/Entity/PlentymarketsImportEntityItem.php
This pull request fix my last pull request #73 
The var $data was set 2x and caused an sql error, because the number of tokens in the sql statement was wrong.
=> hotfix for my last pull request #73

CHANGELOG.md
| Bug fix?        | no
added a changelog to the 1.9 branch
we had none
=> added a changelog

Components/Import/Entity/PlentymarketsImportEntityItemPrice.php
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | yes
This commit add the event PlentyConnector_ImportEntityItemPrice_BeforeSavePrice to the price entity class.
The event is only in the item entity class.
=> add the new event

CHANGELOG.md
| Bug fix?        | no|yes
| New feature?    | no|yes
| BC breaks?      | no|yes
| Deprecations?   | no|yes
Which problem does the PR fix? (remove this section if you linked an issue above)
=> change changelog to last commit

Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Media/HandleMediaCommandHandler.php
Remove the Identity of a Media if its not longer existing in Shopware.
plentyconnector.ERROR: Media by id 145 not found
=> Added Exception if Media was deleted in Shopware

Adapter/PlentymarketsAdapter/ServiceBus/CommandHandler/Order/HandleOrderCommandHandler.php, Adapter/ShopwareAdapter/ResponseParser/Address/AddressResponseParser.php, Connector/TransferObject/Order/Address/Address.php
| Bug fix?        | no
| New feature?    | yes
=> Development sync

Components/PayPal/Plentymarkets/PayPalPlusInvoiceRequestGenerator.php
| Bug fix?        |yes
| Related tickets | fixes #133
fixes the issue 133
=> fixed the paypal plus invoice parameter names

Adapter/PlentymarketsAdapter/ServiceBus/CommandHandler/Order/HandleOrderCommandHandler.php, Adapter/ShopwareAdapter/ResponseParser/Customer/CustomerResponseParser.php, Connector/TransferObject/Order/Customer/Customer.php, tests/Unit/Adapter/ShopwareAdapter/ResponseParser/Customer/CustomerResponseParserTest.php
| Related tickets | fixes #136 
=> export correct customer types; fixes #136

Adapter/PlentymarketsAdapter/ServiceBus/CommandHandler/Order/HandleOrderCommandHandler.php, Connector/MappingService/MappingService.php
| Bug fix?        |yes
| Related tickets | fixes #132
fixes issue #132
=> removed the forced sorting of mapping data

Adapter/PlentymarketsAdapter/ResponseParser/Order/OrderResponseParser.php, Adapter/PlentymarketsAdapter/ServiceBus/CommandHandler/Order/HandleOrderCommandHandler.php, Adapter/ShopwareAdapter/ResponseParser/Customer/CustomerResponseParser.php, Connector/TransferObject/Order/Customer/Customer.php, tests/Unit/Adapter/ShopwareAdapter/ResponseParser/Customer/CustomerResponseParserTest.php
| Bug fix?        |yes
| New feature?    |yes
| BC breaks?      |yes
| Related tickets | #138 
added a basic newsletter sync
=> added a basic the newsletter synchronization

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .travis.yml
=> Update GitHub templates

Adapter/PlentymarketsAdapter/ResponseParser/Category/CategoryResponseParser.php, CHANGELOG.md
added a missing use statement in CategoryResponseParser
=> Missing exception use

Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php, CHANGELOG.md
=> convert gram to kg

Adapter/PlentymarketsAdapter/ResponseParser/Category/CategoryResponseParser.php, CHANGELOG.md
get correct category translation
=> Category translation fix

Adapter/PlentymarketsAdapter/ResponseParser/Category/CategoryResponseParser.php, Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php, CHANGELOG.md
- use correct tax when transferring order to plenty
=> B2 b vat fix

Adapter/PlentymarketsAdapter/ResponseParser/Product/Stock/StockResponseParser.php, CHANGELOG.md
Fix calculation of bundle articles and atricles include in bundles.
| BC breaks?                | no|yes
| Deprecations?             | no|yes
| Tests exists and pass?    | yes/no
| Related tickets           | fixes #X, partially #Y, mentioned in #Z
Which problem does the PR fix? (remove this section if you linked an issue above)
``` php
// If you added new features, show examples of how to use them here
// (remove this section if not a new feature)
$foo = new Foo();
// Now we can do
$foo->doSomething();
```
=> Fix Stock calculation

Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php
=> remove round

Connector/ServiceBus/ValidatorMiddleware/ValidatorMiddleware.php
| BC breaks?                | yes
| Deprecations?             | yes
=> Correct validator middleware

Adapter/PlentymarketsAdapter/ReadApi/Address/Address.php, Adapter/PlentymarketsAdapter/ReadApi/Comment/Comment.php, Adapter/PlentymarketsAdapter/ReadApi/Customer/Customer.php, Adapter/PlentymarketsAdapter/ReadApi/Order/Order.php, Adapter/PlentymarketsAdapter/ReadApi/Payment/Payment.php, Adapter/PlentymarketsAdapter/ServiceBus/ChangedDateTimeTrait.php, Adapter/ShopwareAdapter/ServiceBus/ChangedDateTimeTrait.php, Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Category/HandleCategoryCommandHandler.php, Connector/ServiceBus/ValidatorMiddleware/ValidatorMiddleware.php
=> Cleanup unused stuff

Adapter/ShopwareAdapter/ServiceBus/CommandHandler/MediaCategory/HandleMediaCategoryCommandHandler.php, CHANGELOG.md
=> error by mediaCategory create

Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php, CHANGELOG.md, Connector/TransferObject/Product/Variation/Variation.php, Connector/Validator/Product/Variation/VariationValidator.php
=> Valid weight fix

Components/Bundle/ShopwareAdapter/CommandHandler/HandleBundleCommandHandler.php
- stop customer groups being removed
=> stop customer groups being removed

Adapter/PlentymarketsAdapter/ResponseParser/Category/CategoryResponseParser.php, CHANGELOG.md
- Category content will not be overwritten by default plenty ID
=> Category content will not be overwritten by default plenty ID

Adapter/PlentymarketsAdapter/Helper/MediaCategoryHelper.php, Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, CHANGELOG.md, Connector/BacklogService/Model/Backlog.php, Connector/ServiceBus/CommandType.php, Connector/ServiceBus/QueryType.php, Connector/TransferObject/Order/Address/Address.php, Connector/TransferObject/Order/Comment/Comment.php, Connector/TransferObject/Order/Customer/Customer.php, Connector/TransferObject/Order/Order.php, Connector/TransferObject/Order/OrderItem/OrderItem.php, Connector/TransferObject/Product/Barcode/Barcode.php, Connector/TransferObject/Product/LinkedProduct/LinkedProduct.php, PlentyConnector.php, plugin.xml
=> ## [4.2.1]

Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php, CHANGELOG.md
prepareOrderItems validation fix
=> prepareOrderItems validation fix

Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php, CHANGELOG.md
=> Prepare order item validation error

Adapter/ShopwareAdapter/RequestGenerator/Media/MediaRequestGenerator.php, CHANGELOG.md
=> alternate media text

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, CHANGELOG.md
only transfer variations if has valid clientid
=> only transfer variations with valid clientid

Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php, CHANGELOG.md
use correct item tax when transferring order to plenty
=> use correct item tax when transferring order to plenty

CHANGELOG.md, DependencyInjection/services.xml
- new process priority (orders first)
=> Process priority

Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php, CHANGELOG.md
some small enhancement to reduce function complexity
=> Optimize order item parsing

Adapter/PlentymarketsAdapter/ResponseParser/OrderStatus/OrderStatusResponseParser.php, Adapter/PlentymarketsAdapter/ResponseParser/PaymentStatus/PaymentStatusResponseParser.php
Fix of OrderStatus and PaymentStatus Mapping
Not working in shopware. Wrong and missing attributes.
=> Fix of OrderStatus and PaymentStatus Mapping

Adapter/PlentymarketsAdapter/ResponseParser/OrderStatus/OrderStatusResponseParser.php, Adapter/PlentymarketsAdapter/ResponseParser/PaymentStatus/PaymentStatusResponseParser.php, CHANGELOG.md
Changelog and code optimization
=> Status fix

composer.json, composer.lock
| Deprecations?             | yes
| Tests exists and pass?    | no
Just a small dependency update
=> composer dependency update

Adapter/PlentymarketsAdapter/Helper/VariationHelper.php, Adapter/PlentymarketsAdapter/ResponseParser/Category/CategoryResponseParser.php, Adapter/PlentymarketsAdapter/ResponseParser/Order/OrderResponseParser.php, Adapter/PlentymarketsAdapter/ResponseParser/Product/Price/PriceResponseParser.php, Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php, Adapter/ShopwareAdapter/ResponseParser/Payment/PaymentResponseParser.php, CHANGELOG.md, Connector/IdentityService/IdentityService.php, Connector/IdentityService/IdentityServiceInterface.php, tests/Unit/Adapter/PlentymarketsAdapter/RequestGenerator/RequestGeneratorTest.php, tests/Unit/Adapter/ShopwareAdapter/ResponseParser/ResponseParserTest.php
| BC breaks?                | yes
=> Identity mapping

Adapter/PlentymarketsAdapter/RequestGenerator/Order/Address/AddressRequestGenerator.php, Adapter/PlentymarketsAdapter/RequestGenerator/Order/Customer/CustomerRequestGenerator.php, Adapter/PlentymarketsAdapter/ResponseParser/Order/OrderResponseParser.php, Adapter/ShopwareAdapter/ResponseParser/Address/AddressResponseParser.php, Adapter/ShopwareAdapter/ResponseParser/Customer/CustomerResponseParser.php, CHANGELOG.md, Connector/TransferObject/Order/Address/Address.php, Connector/TransferObject/Order/Customer/Customer.php, Connector/Validator/Order/Address/AddressValidator.php, Connector/Validator/Order/Customer/CustomerValidator.php, tests/Unit/Adapter/ShopwareAdapter/ResponseParser/Address/AddressResponseParserTest.php, tests/Unit/Adapter/ShopwareAdapter/ResponseParser/Customer/CustomerResponseParserTest.php
=> Salutation fix

Adapter/PlentymarketsAdapter/RequestGenerator/Order/Address/AddressRequestGenerator.php
added vat id to billing address
=> add vatid to address

Adapter/PlentymarketsAdapter/ServiceBus/CommandHandler/Payment/HandlePaymentCommandHandler.php, Adapter/ShopwareAdapter/DependencyInjection/services.xml, Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php, Adapter/ShopwareAdapter/ResponseParser/OrderItem/OrderItemResponseParser.php, CHANGELOG.md, Components/PayPal/Plentymarkets/PayPalInstallmentRequestGenerator.php, Components/PayPal/Plentymarkets/PayPalPlusInvoiceRequestGenerator.php, tests/Unit/Adapter/PlentymarketsAdapter/RequestGenerator/Payment/PaymentRequestGeneratorTest.php, tests/Unit/Components/PayPal/Shopware/PayPalInstallmentRequestGeneratorTest.php, tests/Unit/Components/PayPal/Shopware/PayPalPlusInvoiceRequestGeneratorTest.php
=> Paypal data corrections

CHANGELOG.md, Components/Bundle/DependencyInjection/services.xml, Components/Bundle/PlentymarketsAdapter/RequestGenerator/Order/OrderItem/OrderItemRequestGenerator.php, Components/Bundle/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php
corrected the order export with bundles
=> Bundle order item fix

Adapter/ShopwareAdapter/RequestGenerator/Product/ProductRequestGenerator.php, CHANGELOG.md
=> Set change time

Adapter/PlentymarketsAdapter/ResponseParser/Category/CategoryResponseParser.php, Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Category/HandleCategoryCommandHandler.php, CHANGELOG.md
transfer category description 2 as attribute to shopware
=> Second category description

Adapter/ShopwareAdapter/ResponseParser/Address/AddressResponseParser.php
=> fix the gender problem

Adapter/PlentymarketsAdapter/DependencyInjection/services.xml, Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, CHANGELOG.md, Resources/Views/backend/plenty_connector/model/settings.js, Resources/Views/backend/plenty_connector/view/settings.js, Resources/snippets/backend/plentyconnector/main.ini
| issue or Enhancement      | inhancement
- optional check if mainvariation is active
=> Check active mainvariation

Components/Bundle/PlentymarketsAdapter/RequestGenerator/Order/OrderItem/OrderItemRequestGenerator.php
Undefined index fix in bundle order
=> order bundleItem fix

Adapter/ShopwareAdapter/ResponseParser/Customer/CustomerResponseParser.php
=> Add this to fix the gender problem

Adapter/PlentymarketsAdapter/RequestGenerator/Order/OrderRequestGenerator.php, CHANGELOG.md
=> fixed search for an existing customer

Adapter/PlentymarketsAdapter/ResponseParser/Category/CategoryResponseParser.php, Adapter/PlentymarketsAdapter/ResponseParser/Product/Price/PriceResponseParser.php, CHANGELOG.md
- fixed price origin configuration
=> Price origin fix and missing img id

CHANGELOG.md, plugin.xml
=> version +1

Adapter/ShopwareAdapter/RequestGenerator/Product/ProductRequestGenerator.php, CHANGELOG.md, Components/PayPal/Shopware/PayPalInstallmentPaymentResponseParser.php
- item notification is set correctly
=> Item notification fix

Adapter/ShopwareAdapter/DataPersister/Translation/TranslationDataPersister.php, Adapter/ShopwareAdapter/DataProvider/Translation/TranslationDataProvider.php, Adapter/ShopwareAdapter/DataProvider/Translation/TranslationDataProviderInterface.php, CHANGELOG.md
- translated variation configurator
=> translated variation configurator

Adapter/ShopwareAdapter/DataPersister/Translation/TranslationDataPersister.php, CHANGELOG.md
- translated short and technical description
=> translated short and technical description

Adapter/ShopwareAdapter/RequestGenerator/Product/ProductRequestGenerator.php
This PR fix an issue to not set duplicate seo categories of an product.
=> don't set duplicate product seo categories

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, Adapter/ShopwareAdapter/RequestGenerator/Product/ProductRequestGenerator.php, CHANGELOG.md, Connector/TransferObject/Product/Product.php, Connector/Validator/Product/ProductValidator.php
- transfer top seller badge to shopware
=> top seller badge

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, Adapter/ShopwareAdapter/RequestGenerator/Product/ProductRequestGenerator.php, Connector/TransferObject/Product/Badge/Badge.php, Connector/TransferObject/Product/Product.php, Connector/TransferObject/TransferObjectInterface.php, Connector/Validator/Product/Badge/BadgeValidator.php, Connector/Validator/Product/ProductValidator.php
changes the highlight flag mixup to a propper badge value object
=> better badge handling for shopwares highlight flag

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, Connector/Validator/Product/Badge/BadgeValidator.php
=> validator fix

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, Adapter/ShopwareAdapter/RequestGenerator/Product/ProductRequestGenerator.php, Connector/Validator/Product/Badge/BadgeValidator.php
=> Set category fix

CHANGELOG.md, Connector/BacklogService/BacklogService.php, Connector/BacklogService/Command/HandleBacklogElementCommand.php, Connector/BacklogService/Model/Backlog.php, Connector/CleanupService/CleanupService.php, Connector/Connector.php, Connector/ServiceBus/Command/CommandInterface.php, Connector/ServiceBus/Command/TransferObjectCommand.php, Connector/ServiceBus/CommandFactory/CommandFactory.php, Connector/ServiceBus/CommandFactory/CommandFactoryInterface.php, Connector/ValueObject/Definition/Definition.php, Console/Command/BacklogProcessCommand.php, Console/Command/CleanupCommand.php, Console/Command/MappingCommand.php, Console/Command/ProcessCommand.php, Subscriber/CronjobSubscriber.php, composer.json, tests/Unit/Connector/ConnectorTest.php
adds the definition priority to commands and respects that priority when pulling them from the backlog table
DEPENDS ON: https://github.com/plentymarkets/plentymarkets-shopware-connector/pull/357
=> Command priority

CHANGELOG.md, Components/Bundle/PlentymarketsAdapter/ResponseParser/BundleResponseParser.php
=> ´set correct bundle position

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php
=> use configService

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Product/HandleProductCommandHandler.php
=> remove product in shopware fix

CHANGELOG.md, DependencyInjection/services.xml
This PR fix an update issue for the plugin console commands.
=> fix service.xml for shopware 5.5.x

Connector/Validator/Category/CategoryValidator.php
| issue or Enhancement      | issue and Enhancement
- Fixed wrong Category validation output for ShopIdentifiers
- Added missing Category validation for parentIdentifier
=> Fixed wrong Category validation output + added missing Category validation

Adapter/PlentymarketsAdapter/ServiceBus/QueryHandler/Stock/FetchChangedStocksQueryHandler.php, CHANGELOG.md, composer.json, composer.lock
enhances the way stock changes are fetched
=> optimized the stock handling performance

Connector/Validator/Identity/IdentityValidator.php, Connector/Validator/Product/Badge/BadgeValidator.php
=> correct validator path

Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php, Adapter/ShopwareAdapter/ResponseParser/Payment/PaymentResponseParser.php, CHANGELOG.md, tests/Unit/Adapter/ShopwareAdapter/ResponseParser/Payment/PaymentResponseParserTest.php
=> don't write already transfered payments and orders into backlog

.travis.yml, Adapter/ShopwareAdapter/DataPersister/Translation/TranslationDataPersister.php, composer.json
=> correct travis integration

Connector/CleanupService/CleanupService.php
=> cleanup log

PlentyConnector.php
=> fix translations

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php
=> fix variations

Adapter/ShopwareAdapter/DataPersister/Translation/TranslationDataPersister.php, CHANGELOG.md
| issue or Enhancement      ||Enhancement
=> translation optimization

CHANGELOG.md, composer.lock
=> composer.lock

Adapter/ShopwareAdapter/ResponseParser/Payment/PaymentResponseParser.php, CHANGELOG.md
- transfer payment without transactionid
=> transaction fix

Adapter/ShopwareAdapter/RequestGenerator/Product/ProductRequestGenerator.php, CHANGELOG.md
=> Repository

CHANGELOG.md
=> update changelog (multiple product properties)

Adapter/ShopwareAdapter/RequestGenerator/Product/ProductRequestGenerator.php
This PR fix the product category relations for shopware setups with other category depth and subshop relation.
URL to the issue:
https://forum.plentymarkets.com/t/abgleich-der-artikel-nur-noch-ohne-kategorie/517313/87
=> fix product category relations

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, CHANGELOG.md
This PR fix the check for the config setting to check the active status of the main variation for the whole product.
=> fix for checking active main variation

CHANGELOG.md
=> update changelog for the product category relation fix

CHANGELOG.md, DependencyInjection/services.xml, Subscriber/CronjobSubscriber.php
| issue or Enhancement      | issue and Enhancement
This PR change the cronjob scheduler to avoid errors on parallel running cronjobs.
=> change the cronjob scheduler to avoid errors on parallel running cronjobs

autoload.php
=> correct autoload handling when used via composer

README.md
Change the minversion of shopware to the actual master plugin.xml.
=> update readme for the minversion of shopware

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, Connector/Console/Command/DumpCommand.php
=> dump debugging

CHANGELOG.md, Connector/Validator/Order/OrderValidator.php, Connector/ValidatorService/ValidatorService.php
=> DateTime Validation fix

Connector/MappingService/MappingService.php
=> mapping problem

Connector/TransferObject/Product/Badge/Badge.php, Connector/ValidatorService/ValidatorService.php
=> skip badge Validation

CHANGELOG.md, plugin.xml
=> Version update

Adapter/PlentymarketsAdapter/Helper/VariationHelper.php, Adapter/PlentymarketsAdapter/Helper/VariationHelperInterface.php, Adapter/PlentymarketsAdapter/ReadApi/Category/Category.php, Adapter/PlentymarketsAdapter/ReadApi/Item.php, Adapter/PlentymarketsAdapter/ReadApi/Item/Variation.php, Adapter/PlentymarketsAdapter/ReadApi/Order/Order.php, Adapter/PlentymarketsAdapter/RequestGenerator/Order/OrderRequestGenerator.php, Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php, Adapter/ShopwareAdapter/ResponseParser/OrderItem/OrderItemResponseParser.php, Components/Bundle/ShopwareAdapter/CommandHandler/HandleBundleCommandHandler.php, Components/PayPal/Shopware/PayPalUnifiedInstallmentPaymentResponseParser.php, Connector/IdentityService/Storage/IdentityServiceStorageInterface.php, Resources/Views/backend/plenty_connector/controller/actions.js, Resources/menu.xml, plugin.xml
=> Optimization

Adapter/PlentymarketsAdapter/ResponseParser/Product/Image/ImageResponseParser.php, Adapter/PlentymarketsAdapter/ServiceBus/QueryHandler/Category/FetchChangedCategoriesQueryHandler.php, Adapter/ShopwareAdapter/DataPersister/Translation/TranslationDataPersister.php, Adapter/ShopwareAdapter/DataPersister/Translation/TranslationDataPersisterInterface.php, Adapter/ShopwareAdapter/DataProvider/Translation/TranslationDataProvider.php, Adapter/ShopwareAdapter/DataProvider/Translation/TranslationDataProviderInterface.php, Adapter/ShopwareAdapter/DependencyInjection/services.xml, Adapter/ShopwareAdapter/ResponseParser/OrderItem/OrderItemResponseParser.php, Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Product/HandleProductCommandHandler.php, CHANGELOG.md, Connector/TransferObject/Product/Image/Image.php
=> Image translation

Adapter/PlentymarketsAdapter/Helper/VariationHelper.php
=> fixed Call to a member function getNumber() on boolean error

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, Connector/TransferObject/Product/Product.php
=> CreatedAtDate 

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php, Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Product/HandleProductCommandHandler.php, CHANGELOG.md, Connector/ValidatorService/ValidatorService.php
fix error after changed mainvariationnumber (@Pfabeck)
=> fixed error

CHANGELOG.md, Components/CustomProducts/DependencyInjection/services.xml, Components/CustomProducts/ShopwareAdapter/ResponseParser/Order/DecoratedOrderItemResponseParser.php, Components/CustomProducts/ShopwareAdapter/ResponseParser/Order/OrderItemResponseParser.php, PlentyConnector.php
- export custom products options as order items
=> custom products order items

Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php, CHANGELOG.md, Connector/TransferObject/Product/Product.php
=> multipack fix

Adapter/PlentymarketsAdapter/DependencyInjection/services.xml, Adapter/PlentymarketsAdapter/ResponseParser/Product/Price/PriceResponseParser.php, Adapter/PlentymarketsAdapter/ServiceBus/QueryHandler/Price/FetchAllPricesQueryHandler.php, Adapter/PlentymarketsAdapter/ServiceBus/QueryHandler/Price/FetchChangedPricesQueryHandler.php, Adapter/ShopwareAdapter/DataProvider/CustomerGroup/CustomerGroupDataProvider.php, Adapter/ShopwareAdapter/DataProvider/CustomerGroup/CustomerGroupDataProviderInterface.php, Adapter/ShopwareAdapter/DependencyInjection/services.xml, Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Price/HandlePriceCommandHandler.php, CHANGELOG.md, Connector/TransferObject/Product/Price/Price.php, DependencyInjection/definitions.xml
=> Price command handler

DependencyInjection/definitions.xml
=> definitions

Components/AmazonPay/Shopware/AmazonPayPaymentResponseParser.php, DependencyInjection/definitions.xml
=> Amazon pay fix

CHANGELOG.md, Components/Bundle/ShopwareAdapter/CommandHandler/HandleBundleCommandHandler.php
=> Bundle variation limit

Adapter/PlentymarketsAdapter/ResponseParser/Product/Price/PriceResponseParser.php, CHANGELOG.md
=> Price referrer fix

Adapter/PlentymarketsAdapter/ResponseParser/Product/Image/ImageResponseParser.php
=> image exception

Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Category/HandleCategoryCommandHandler.php
=> strict mode

Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Media/HandleMediaCommandHandler.php
This PR remove the duplicate action to save the media attributes.
=> remove duplicates

Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php, CHANGELOG.md
variant properties are now transferred as attribute (beta feature)
=> Properties as attribute

Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php, Adapter/ShopwareAdapter/DataPersister/Attribute/AttributeDataPersister.php, Connector/Validator/Attribute/AttributeValidator.php, Connector/ValueObject/Attribute/Attribute.php
=> optional attribute type

Adapter/ShopwareAdapter/DataProvider/Tax/TaxDataProvider.php, Adapter/ShopwareAdapter/DataProvider/Tax/TaxDataProviderInterface.php, Adapter/ShopwareAdapter/DependencyInjection/services.xml, Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php, Adapter/ShopwareAdapter/ResponseParser/OrderItem/OrderItemResponseParser.php, CHANGELOG.md
=> tax handling refactored

Adapter/ShopwareAdapter/DependencyInjection/services.xml, Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php
fix empty invoiceShippingTaxRate
=> fix empty invoiceShippingTaxRate

Adapter/PlentymarketsAdapter/RequestGenerator/Order/OrderItem/OrderItemRequestGenerator.php, CHANGELOG.md
remove item variation id at vouchers and discounts @jochenmanz
=> remove item variation id at vouchers and discounts

Adapter/PlentymarketsAdapter/Client/Client.php, plugin.xml
=> throw rest response on error

Adapter/PlentymarketsAdapter/ResponseParser/Order/OrderResponseParser.php
getCustomerGroupIdentity() typehint remove
=> getCustomerGroupIdentity() typehint remove

Components/AmazonPay/Shopware/AmazonPayPaymentResponseParser.php
=> amazonPayFix

Adapter/ShopwareAdapter/ResponseParser/OrderItem/OrderItemResponseParser.php, CHANGELOG.md
taxRepository couldn't get found because of too aggressiv type casting
=> #fix wrong float cast

Adapter/PlentymarketsAdapter/ResponseParser/Manufacturer/ManufacturerResponseParser.php, Adapter/ShopwareAdapter/DependencyInjection/services.xml, Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Manufacturer/HandleManufacturerCommandHandler.php, CHANGELOG.md, Connector/TransferObject/Manufacturer/Manufacturer.php
- additional manufacturer information as attributes (@Pfabeck)
=> add manufacturer attributes

Adapter/PlentymarketsAdapter/ResponseParser/Manufacturer/ManufacturerResponseParser.php
| issue or Enhancement      ||Enhancement
- add manufacturer external name as attribute
=> add manufacturer external name as attribute

Adapter/PlentymarketsAdapter/DependencyInjection/services.xml, Adapter/PlentymarketsAdapter/RequestGenerator/Payment/PaymentRequestGenerator.php, CHANGELOG.md, Resources/Views/backend/plenty_connector/model/settings.js, Resources/Views/backend/plenty_connector/view/settings.js, Resources/snippets/backend/plentyconnector/main.ini
| issue or Enhancement     |Enhancement
- add system currency to config
=> add system currency to config

Adapter/PlentymarketsAdapter/Client/Client.php, CHANGELOG.md
| Changelog updated?        |yes
- curl_setopt($curl, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4) @florianliebig
=>  CURL_IPRESOLVE_V4

Adapter/PlentymarketsAdapter/ResponseParser/Order/OrderResponseParser.php
- Fixed 'Customer::getGender() must be of the type string, null returned' error
=> null check on customer gender

Adapter/PlentymarketsAdapter/ResponseParser/Order/OrderResponseParser.php, CHANGELOG.md, Connector/Validator/Product/ProductValidator.php
- set shipping time on multi package order (@Pfabeck)
- set shipping time equal today if not given (@Pfabeck)
=> set shipping time on multi package order

Adapter/PlentymarketsAdapter/Client/Client.php, CHANGELOG.md
- fixed client for put calls (@Pfabeck)
=> fixed client for put calls

Adapter/PlentymarketsAdapter/ResponseParser/Order/OrderResponseParser.php
- skip not existing articles in order response parser
=> skip not existing articles in order response parser
