Components/Import/Entity/PlentymarketsImportEntityItem.php

The translations of an article must be saved in the database table 's_articles_translations'. This entries are in use for the seo logic.

fix article translation

---

Components/Export/Continuous/Entity/PlentymarketsExportEntityOrder.php

Transfer IBAN, BIC and so on to Plentymarkets.
Shopware stores this information at the order. Plentymarkets stores this information at the customer.
But we need at least IBAN and BIC from the last order to make a debit.

Update PlentymarketsExportEntityOrder.php for SEPA Support

---

Components/Import/Entity/PlentymarketsImportEntityItem.php
Controllers/Backend/Plentymarkets.php
Views/backend/plentymarkets/model/settings.js
Views/backend/plentymarkets/view/settings.js

Shopware 5 made it easy to choose a different selection format for the variants. I added a small configuration option inside the PlentyConnector as this has to be set foreach product individually.

added a configure option for the configurator type

---

Components/Import/Entity/PlentymarketsImportEntityItemImage.php

Small Bugfix from one of our customer forks, the thumbnails are generated automatically when saving the model. The version_compare was switched to only when the Shopware version is lower then 4.2, the old generation method is used.

thumbnails are generated twice on Shopware > 4.2

---

Components/Import/Entity/PlentymarketsImportEntityItemImage.php

If the exists variant image mappings are not deleted before fetching the current variant image mappings from plenty, the exists mappings in the sw db multiplicated with each item image update.

delete all variant image mappings of an item

---

Components/Import/Entity/PlentymarketsImportEntityItem.php

if the field "inStock" is empty / not set, the variant is not selectable on the frontend.

fix variant settings

---

Components/Import/PlentymarketsImportItemHelper.php

Shopware has changed the allowed product number regex in 5.0.2, attached a small pr to change the regex when Shopware is running in that version or newer. 
From their upgrade.md:
"It's no longer possible to have spaces in article numbers. Existing articles with spaces in their numbers will still work, but the article cannot be changed without fixing the number."

changed the product number regex for Shopware > 5.0.2

---

Components/Import/Entity/PlentymarketsImportEntityItem.php

to set the addtionaltext for a variant is deprecated since shopware version >= 5.0.0

item import - setting the additionaltext for a variant

---

Adapter/PlentymarketsAdapter/QueryBus/QueryHandler/Manufacturer/FetchManufacturerQueryHandler.php
Connector/IdentityService/IdentityService.php
Connector/IdentityService/Storage/DoctrineIdentityStorage.php
Connector/IdentityService/Storage/IdentityStorageInterface.php

The objectType is necessary to uniquely identify identities since it is not guaranteed that adapterIdentifier is unique across different types.

Adds objectType to removeIdentity and fixes wrong adapter name

---

Components/Import/Entity/PlentymarketsImportEntityItem.php

| New feature?    | no|yes
| Related tickets | https://forum.plentymarkets.com/t/shopware-artikelbeschreibung-wird-trotz-der-einstellung-beschreibung-nicht-uebernehmen-von-plentymarkets-ueberschrieben/45842/2
This commit change in article sync with the following improvement:
add only the article texts, which are activated in the import settings.
If the sync of item texts is deactivated, the content will be set to empty on import.

change article sync (article texts)

---

Components/Import/Entity/PlentymarketsImportEntityItem.php

| New feature?    | yes
This commit add the event PlentyConnector_ImportEntityItemPrice_BeforeSavePrice directly to the item import, because this event is only triggered, if the price was saved over the import entity item price.
(see above)

add event PlentyConnector_ImportEntityItemPrice_BeforeSavePrice

---

Components/Import/Entity/PlentymarketsImportEntityItem.php

| Bug fix?        | no
This commit change the method setVariants to set always the number of the detail, to use it on other events.
Before, the detail number is only set, if the detail was not created.
For example, the event PlentyConnector_ImportEntityItemPrice_BeforeSavePrice need the detail number.

change method setVariants

---

Adapter/PlentymarketsAdapter/Client/Client.php

| Related tickets | partially #80
Pass `itemsPerPage`and `page` to REST requests.
The parameters page and itemsPerPage have been correctly calculated. However, the parameters were not passed to REST request, causing always only the first page to be returned for large responses.

REST requests: Pass (itemsPer)Page params

---

Adapter/PlentymarketsAdapter/ReadApi/Item.php

| Related tickets | partially #80
Use the `client->getIterator` method to retrieve all items, not only the first 50 items (first page).
During the synchronization, only the first 50 articles have been synced.
I did a search and it appears that besides the manufactures and now the articles/items, no requests makes use of `client->getIterator`. This will probably lead to problems, if there are more entities of one kind (e.g. categories).

ReadApi\Item: Retrieve all items

---

Adapter/PlentymarketsAdapter/ResponseParser/Category/CategoryResponseParser.php
Adapter/PlentymarketsAdapter/ResponseParser/Order/OrderResponseParser.php
Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php
Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php
Adapter/ShopwareAdapter/ResponseParser/Payment/PaymentResponseParser.php
CHANGELOG.md
Connector/IdentityService/IdentityService.php
Connector/IdentityService/IdentityServiceInterface.php
Connector/TransferObject/Payment/Payment.php
Connector/Validator/Order/Payment/PaymentValidator.php

| BC breaks?                | yes
added a check to only transfer product or orders when at least one of the shops has a mapped shop on the other adapter
products will not be imported if the shop is not mapped, but their images will be transported. This will lead to a excessive amount of data transfered.

Add mapping check

---

Adapter/PlentymarketsAdapter/RequestGenerator/Order/Address/AddressRequestGenerator.php
CHANGELOG.md

| Tests exists and pass?    | no
added a missing use statement
mybe optimizes the address splitting to behave better with missing house numbers

missing use statement when handling address splitting errors

---

Adapter/PlentymarketsAdapter/Helper/ReferenceAmountCalculator.php

changes the loading time of units used in the reference amout  calculator
when the call limit is reached, the class cannot be instantiated and so completely brocken as the class is instantiated when the container is build.

do not load units during container initialization

---

Adapter/PlentymarketsAdapter/ServiceBus/CommandHandler/Payment/HandlePaymentCommandHandler.php
CHANGELOG.md
Documentation/ErrorHandling.md

| Changelog updated?        |yes
Payments are not transferred to plenty, when a payment with the same transaction id exists.
In some cases when a PayPal payment is already captured in plenty and the payment transferral from shopware is delayed a second payment will be added to the order in plenty.

Fix duplicate PayPal payment transferral to plenty

---

Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php
CHANGELOG.md

| BC breaks?                | no|yes
| Deprecations?             | no|yes
This PR adds a fallback for the weight-mapping inside the _VariationResponseParser_. If the variant has no _weightNetG_ given, it tries now to use _weightG_. 
Some customers are using only one of the weight columns

add fallback for weight to VariantResponseParser

---

Adapter/PlentymarketsAdapter/ResponseParser/Order/OrderResponseParser.php
Adapter/PlentymarketsAdapter/ServiceBus/CommandHandler/Order/HandleOrderCommandHandler.php
Adapter/ShopwareAdapter/DependencyInjection/services.xml
Adapter/ShopwareAdapter/ResponseParser/Order/OrderResponseParser.php
Adapter/ShopwareAdapter/ResponseParser/OrderItem/OrderItemResponseParser.php
CHANGELOG.md
Connector/TransferObject/Order/OrderItem/OrderItem.php
tests/Unit/Adapter/ShopwareAdapter/ResponseParser/OrderItem/OrderItemResponseParserTest.php

| Changelog updated?        |yes
| Tests exists and pass?    |no
| Related tickets           | related #125
All order item prices are passed as brutto prices according to the default tax rate of the tax rule (e.g. full tax rate -> 19% for orders with german tax).
For third country orders e.g. from Swiss with the full tax rate prices were calculated wrongly in plentymarkets.

Fix brutto netto order prices for 0 tax orders

---

Components/Sepa/Shopware/SepaPaymentResponseParser.php

SEPA payments are only transferred to plentymarkets if an account holder is present in the payment instance. Shopware does not ask for an account holder for SEPA payments by default, so all the SEPA payments are blocked from transfer. This PR removes that necessity for an account holder.

Removes necessity for an account holder for sepa payments

---

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php
Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php
Adapter/ShopwareAdapter/RequestGenerator/Product/Variation/VariationRequestGenerator.php
CHANGELOG.md
Connector/TransferObject/Product/Variation/Variation.php

This PR fix the last stock settings for variations and set only the flag on the product, if all variations have set the flag in plentymarkets.

Fix variation laststock

---

Adapter/PlentymarketsAdapter/DependencyInjection/services.xml
Adapter/PlentymarketsAdapter/Helper/VariationHelper.php
Adapter/PlentymarketsAdapter/Helper/VariationHelperInterface.php
Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php
Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php
Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Variation/HandleVariationCommandHandler.php
CHANGELOG.md

| issue or Enhancement      | issue+Enhancement
This PR has the following changes for the main variation relation ship:
1.) I found a issue, that allways the sync linked the first variation as main variation. If a product has more then one variation, but only one variation is active, the product is not displayed on the store. A inactive variation is the main variation, but if the main variation is not active, the product is not active in the store.
I fixed it in the following steps:
- if the config was set, that use the inactive main variation, the product will be inactive.
- if the config was not set, check the main variation is active, take the main …

fix main variation relation ship of an product

---

Adapter/ShopwareAdapter/ServiceBus/CommandHandler/Category/HandleCategoryCommandHandler.php
CHANGELOG.md
plugin.xml

This PR fix the category sync, if more then one shop has the same configured root category.
Actual, the category sync abort with the error "missing parent category".
The change of the command handler will check, if the matched category include the shopware shop root category and will check the attribute field "shopIdentifier" no more.

fix category command handler

---

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php
Adapter/PlentymarketsAdapter/ResponseParser/Product/Variation/VariationResponseParser.php
Adapter/ShopwareAdapter/RequestGenerator/Product/ProductRequestGenerator.php
Connector/TransferObject/Product/Product.php
Connector/Validator/Product/ProductValidator.php

This PR fix the stockLimitation variations without stock management in Plentymarkets and optimize the merged PR https://github.com/plentymarkets/plentymarkets-shopware-connector/pull/407.
The product flag stockLimitation is removed, because since 5.4, the column is deprecated. If the column is set, so Shopware will set this flag for all variations. A other issue is, when a variations has no stockLimitation but the product has the activated flag, Shopware will display an notice, when you add a variation without stockLimitation to the basket. In this case, we should open a issue on the Shopware issue tracker.

fix stockLimitation for variations without stock management

---

Adapter/PlentymarketsAdapter/ResponseParser/Product/ProductResponseParser.php

Since many Plentyshops use the Article ID (not Variant ID) in the SEO-URL it's nice to have the parent article ID in shopware (e.g. for SEO-Routing rules)

Add (parent) Article ID to free-text-fields
